# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140224214828) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "boards", force: true do |t|
    t.integer  "game_id"
    t.integer  "move_num",          limit: 2,                 null: false
    t.integer  "pos",               limit: 2
    t.integer  "ko",                limit: 2
    t.integer  "captured_stones",   limit: 2
    t.boolean  "pass",                        default: false
    t.integer  "seconds_remaining", limit: 2
    t.integer  "time_field_1"
    t.integer  "time_field_2"
    t.boolean  "pos_0"
    t.boolean  "pos_1"
    t.boolean  "pos_2"
    t.boolean  "pos_3"
    t.boolean  "pos_4"
    t.boolean  "pos_5"
    t.boolean  "pos_6"
    t.boolean  "pos_7"
    t.boolean  "pos_8"
    t.boolean  "pos_9"
    t.boolean  "pos_10"
    t.boolean  "pos_11"
    t.boolean  "pos_12"
    t.boolean  "pos_13"
    t.boolean  "pos_14"
    t.boolean  "pos_15"
    t.boolean  "pos_16"
    t.boolean  "pos_17"
    t.boolean  "pos_18"
    t.boolean  "pos_19"
    t.boolean  "pos_20"
    t.boolean  "pos_21"
    t.boolean  "pos_22"
    t.boolean  "pos_23"
    t.boolean  "pos_24"
    t.boolean  "pos_25"
    t.boolean  "pos_26"
    t.boolean  "pos_27"
    t.boolean  "pos_28"
    t.boolean  "pos_29"
    t.boolean  "pos_30"
    t.boolean  "pos_31"
    t.boolean  "pos_32"
    t.boolean  "pos_33"
    t.boolean  "pos_34"
    t.boolean  "pos_35"
    t.boolean  "pos_36"
    t.boolean  "pos_37"
    t.boolean  "pos_38"
    t.boolean  "pos_39"
    t.boolean  "pos_40"
    t.boolean  "pos_41"
    t.boolean  "pos_42"
    t.boolean  "pos_43"
    t.boolean  "pos_44"
    t.boolean  "pos_45"
    t.boolean  "pos_46"
    t.boolean  "pos_47"
    t.boolean  "pos_48"
    t.boolean  "pos_49"
    t.boolean  "pos_50"
    t.boolean  "pos_51"
    t.boolean  "pos_52"
    t.boolean  "pos_53"
    t.boolean  "pos_54"
    t.boolean  "pos_55"
    t.boolean  "pos_56"
    t.boolean  "pos_57"
    t.boolean  "pos_58"
    t.boolean  "pos_59"
    t.boolean  "pos_60"
    t.boolean  "pos_61"
    t.boolean  "pos_62"
    t.boolean  "pos_63"
    t.boolean  "pos_64"
    t.boolean  "pos_65"
    t.boolean  "pos_66"
    t.boolean  "pos_67"
    t.boolean  "pos_68"
    t.boolean  "pos_69"
    t.boolean  "pos_70"
    t.boolean  "pos_71"
    t.boolean  "pos_72"
    t.boolean  "pos_73"
    t.boolean  "pos_74"
    t.boolean  "pos_75"
    t.boolean  "pos_76"
    t.boolean  "pos_77"
    t.boolean  "pos_78"
    t.boolean  "pos_79"
    t.boolean  "pos_80"
    t.boolean  "pos_81"
    t.boolean  "pos_82"
    t.boolean  "pos_83"
    t.boolean  "pos_84"
    t.boolean  "pos_85"
    t.boolean  "pos_86"
    t.boolean  "pos_87"
    t.boolean  "pos_88"
    t.boolean  "pos_89"
    t.boolean  "pos_90"
    t.boolean  "pos_91"
    t.boolean  "pos_92"
    t.boolean  "pos_93"
    t.boolean  "pos_94"
    t.boolean  "pos_95"
    t.boolean  "pos_96"
    t.boolean  "pos_97"
    t.boolean  "pos_98"
    t.boolean  "pos_99"
    t.boolean  "pos_100"
    t.boolean  "pos_101"
    t.boolean  "pos_102"
    t.boolean  "pos_103"
    t.boolean  "pos_104"
    t.boolean  "pos_105"
    t.boolean  "pos_106"
    t.boolean  "pos_107"
    t.boolean  "pos_108"
    t.boolean  "pos_109"
    t.boolean  "pos_110"
    t.boolean  "pos_111"
    t.boolean  "pos_112"
    t.boolean  "pos_113"
    t.boolean  "pos_114"
    t.boolean  "pos_115"
    t.boolean  "pos_116"
    t.boolean  "pos_117"
    t.boolean  "pos_118"
    t.boolean  "pos_119"
    t.boolean  "pos_120"
    t.boolean  "pos_121"
    t.boolean  "pos_122"
    t.boolean  "pos_123"
    t.boolean  "pos_124"
    t.boolean  "pos_125"
    t.boolean  "pos_126"
    t.boolean  "pos_127"
    t.boolean  "pos_128"
    t.boolean  "pos_129"
    t.boolean  "pos_130"
    t.boolean  "pos_131"
    t.boolean  "pos_132"
    t.boolean  "pos_133"
    t.boolean  "pos_134"
    t.boolean  "pos_135"
    t.boolean  "pos_136"
    t.boolean  "pos_137"
    t.boolean  "pos_138"
    t.boolean  "pos_139"
    t.boolean  "pos_140"
    t.boolean  "pos_141"
    t.boolean  "pos_142"
    t.boolean  "pos_143"
    t.boolean  "pos_144"
    t.boolean  "pos_145"
    t.boolean  "pos_146"
    t.boolean  "pos_147"
    t.boolean  "pos_148"
    t.boolean  "pos_149"
    t.boolean  "pos_150"
    t.boolean  "pos_151"
    t.boolean  "pos_152"
    t.boolean  "pos_153"
    t.boolean  "pos_154"
    t.boolean  "pos_155"
    t.boolean  "pos_156"
    t.boolean  "pos_157"
    t.boolean  "pos_158"
    t.boolean  "pos_159"
    t.boolean  "pos_160"
    t.boolean  "pos_161"
    t.boolean  "pos_162"
    t.boolean  "pos_163"
    t.boolean  "pos_164"
    t.boolean  "pos_165"
    t.boolean  "pos_166"
    t.boolean  "pos_167"
    t.boolean  "pos_168"
    t.boolean  "pos_169"
    t.boolean  "pos_170"
    t.boolean  "pos_171"
    t.boolean  "pos_172"
    t.boolean  "pos_173"
    t.boolean  "pos_174"
    t.boolean  "pos_175"
    t.boolean  "pos_176"
    t.boolean  "pos_177"
    t.boolean  "pos_178"
    t.boolean  "pos_179"
    t.boolean  "pos_180"
    t.boolean  "pos_181"
    t.boolean  "pos_182"
    t.boolean  "pos_183"
    t.boolean  "pos_184"
    t.boolean  "pos_185"
    t.boolean  "pos_186"
    t.boolean  "pos_187"
    t.boolean  "pos_188"
    t.boolean  "pos_189"
    t.boolean  "pos_190"
    t.boolean  "pos_191"
    t.boolean  "pos_192"
    t.boolean  "pos_193"
    t.boolean  "pos_194"
    t.boolean  "pos_195"
    t.boolean  "pos_196"
    t.boolean  "pos_197"
    t.boolean  "pos_198"
    t.boolean  "pos_199"
    t.boolean  "pos_200"
    t.boolean  "pos_201"
    t.boolean  "pos_202"
    t.boolean  "pos_203"
    t.boolean  "pos_204"
    t.boolean  "pos_205"
    t.boolean  "pos_206"
    t.boolean  "pos_207"
    t.boolean  "pos_208"
    t.boolean  "pos_209"
    t.boolean  "pos_210"
    t.boolean  "pos_211"
    t.boolean  "pos_212"
    t.boolean  "pos_213"
    t.boolean  "pos_214"
    t.boolean  "pos_215"
    t.boolean  "pos_216"
    t.boolean  "pos_217"
    t.boolean  "pos_218"
    t.boolean  "pos_219"
    t.boolean  "pos_220"
    t.boolean  "pos_221"
    t.boolean  "pos_222"
    t.boolean  "pos_223"
    t.boolean  "pos_224"
    t.boolean  "pos_225"
    t.boolean  "pos_226"
    t.boolean  "pos_227"
    t.boolean  "pos_228"
    t.boolean  "pos_229"
    t.boolean  "pos_230"
    t.boolean  "pos_231"
    t.boolean  "pos_232"
    t.boolean  "pos_233"
    t.boolean  "pos_234"
    t.boolean  "pos_235"
    t.boolean  "pos_236"
    t.boolean  "pos_237"
    t.boolean  "pos_238"
    t.boolean  "pos_239"
    t.boolean  "pos_240"
    t.boolean  "pos_241"
    t.boolean  "pos_242"
    t.boolean  "pos_243"
    t.boolean  "pos_244"
    t.boolean  "pos_245"
    t.boolean  "pos_246"
    t.boolean  "pos_247"
    t.boolean  "pos_248"
    t.boolean  "pos_249"
    t.boolean  "pos_250"
    t.boolean  "pos_251"
    t.boolean  "pos_252"
    t.boolean  "pos_253"
    t.boolean  "pos_254"
    t.boolean  "pos_255"
    t.boolean  "pos_256"
    t.boolean  "pos_257"
    t.boolean  "pos_258"
    t.boolean  "pos_259"
    t.boolean  "pos_260"
    t.boolean  "pos_261"
    t.boolean  "pos_262"
    t.boolean  "pos_263"
    t.boolean  "pos_264"
    t.boolean  "pos_265"
    t.boolean  "pos_266"
    t.boolean  "pos_267"
    t.boolean  "pos_268"
    t.boolean  "pos_269"
    t.boolean  "pos_270"
    t.boolean  "pos_271"
    t.boolean  "pos_272"
    t.boolean  "pos_273"
    t.boolean  "pos_274"
    t.boolean  "pos_275"
    t.boolean  "pos_276"
    t.boolean  "pos_277"
    t.boolean  "pos_278"
    t.boolean  "pos_279"
    t.boolean  "pos_280"
    t.boolean  "pos_281"
    t.boolean  "pos_282"
    t.boolean  "pos_283"
    t.boolean  "pos_284"
    t.boolean  "pos_285"
    t.boolean  "pos_286"
    t.boolean  "pos_287"
    t.boolean  "pos_288"
    t.boolean  "pos_289"
    t.boolean  "pos_290"
    t.boolean  "pos_291"
    t.boolean  "pos_292"
    t.boolean  "pos_293"
    t.boolean  "pos_294"
    t.boolean  "pos_295"
    t.boolean  "pos_296"
    t.boolean  "pos_297"
    t.boolean  "pos_298"
    t.boolean  "pos_299"
    t.boolean  "pos_300"
    t.boolean  "pos_301"
    t.boolean  "pos_302"
    t.boolean  "pos_303"
    t.boolean  "pos_304"
    t.boolean  "pos_305"
    t.boolean  "pos_306"
    t.boolean  "pos_307"
    t.boolean  "pos_308"
    t.boolean  "pos_309"
    t.boolean  "pos_310"
    t.boolean  "pos_311"
    t.boolean  "pos_312"
    t.boolean  "pos_313"
    t.boolean  "pos_314"
    t.boolean  "pos_315"
    t.boolean  "pos_316"
    t.boolean  "pos_317"
    t.boolean  "pos_318"
    t.boolean  "pos_319"
    t.boolean  "pos_320"
    t.boolean  "pos_321"
    t.boolean  "pos_322"
    t.boolean  "pos_323"
    t.boolean  "pos_324"
    t.boolean  "pos_325"
    t.boolean  "pos_326"
    t.boolean  "pos_327"
    t.boolean  "pos_328"
    t.boolean  "pos_329"
    t.boolean  "pos_330"
    t.boolean  "pos_331"
    t.boolean  "pos_332"
    t.boolean  "pos_333"
    t.boolean  "pos_334"
    t.boolean  "pos_335"
    t.boolean  "pos_336"
    t.boolean  "pos_337"
    t.boolean  "pos_338"
    t.boolean  "pos_339"
    t.boolean  "pos_340"
    t.boolean  "pos_341"
    t.boolean  "pos_342"
    t.boolean  "pos_343"
    t.boolean  "pos_344"
    t.boolean  "pos_345"
    t.boolean  "pos_346"
    t.boolean  "pos_347"
    t.boolean  "pos_348"
    t.boolean  "pos_349"
    t.boolean  "pos_350"
    t.boolean  "pos_351"
    t.boolean  "pos_352"
    t.boolean  "pos_353"
    t.boolean  "pos_354"
    t.boolean  "pos_355"
    t.boolean  "pos_356"
    t.boolean  "pos_357"
    t.boolean  "pos_358"
    t.boolean  "pos_359"
    t.boolean  "pos_360"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "boards", ["game_id"], name: "index_boards_on_game_id", using: :btree

  create_table "games", force: true do |t|
    t.integer  "black_player_id"
    t.integer  "white_player_id"
    t.integer  "creator_id",                            null: false
    t.string   "description",                limit: 40
    t.integer  "end_type",                   limit: 2
    t.integer  "board_size",                 limit: 2
    t.integer  "handicap",                   limit: 2
    t.float    "komi"
    t.string   "time_settings",              limit: 40
    t.string   "rule_set",                   limit: 20
    t.integer  "status",                     limit: 2
    t.integer  "mode",                       limit: 2
    t.datetime "started_at"
    t.datetime "finished_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "winner_id"
    t.float    "black_score"
    t.float    "white_score"
    t.text     "dead_stones_serialized"
    t.text     "territory_tiles_serialized"
    t.integer  "black_dead_stone_count",     limit: 2
    t.integer  "white_dead_stone_count",     limit: 2
  end

  add_index "games", ["black_player_id"], name: "index_games_on_black_player_id", using: :btree
  add_index "games", ["white_player_id"], name: "index_games_on_white_player_id", using: :btree
  add_index "games", ["winner_id"], name: "index_games_on_winner_id", using: :btree

  create_table "users", force: true do |t|
    t.string   "username",                    null: false
    t.string   "password_digest"
    t.string   "email",            limit: 50
    t.integer  "status",           limit: 2
    t.integer  "rank",             limit: 2
    t.text     "account_settings"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "users", ["email"], name: "index_users_on_email", using: :btree
  add_index "users", ["username"], name: "index_users_on_username", unique: true, using: :btree

end
